apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "custdatasvc-external-secret"
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: "cluster-secret-store"
    kind: ClusterSecretStore
  target:
    name: secrets-manager-secret
    creationPolicy: Owner
  data:
    - secretKey: "cluster-secret-store"
      remoteRef:
        key: "MONGO_DEV_PWD"
    - secretKey: "cluster-secret-store"
      remoteRef:
        key: "NEW_RELIC_PWD"
        optional: true
