apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "custdatasvc-external-secret"
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: "cluster-secret-store"
    kind: ClusterSecretStore
  dataFrom:
  {{- toYaml .Values.externalSecrets.dataFrom | nindent 4 }}
