apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  labels:
    k8slens-edit-resource-version: v1alpha3
    {{- include "custdatasvc.labels" . | nindent 4 }}
  name: custdatasvc-gateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - "custdatasvc.sevenhillsinfotech.com"
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - "custdatasvc.sevenhillsinfotech.com"
      port:
        name: https-443
        number: 443
        protocol: HTTP